apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::568307822298:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-kojIFx1nBjJR
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-fresher
      userarn: arn:aws:iam::568307822298:user/Pinjari
      username: Pinjari
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-08T05:47:19Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1305"
  uid: d5ab650c-a473-44f8-92ad-874db827d7af